const LEAGUES=[19292,58005,687126,131997];
const state={league:58005,gw:null,compact:null,full:null,sort:{key:'league_rank',dir:1},view:'overview'};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('en-MY').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function getJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${path}`);return r.json()}
async function discover(){
  const available={};
  await Promise.all(LEAGUES.map(async lid=>{available[lid]=[];for(let gw=1;gw<=38;gw++){try{const r=await fetch(`../data/gw${gw}_league${lid}_compact.json`,{method:'HEAD',cache:'no-store'});if(r.ok)available[lid].push(gw)}catch{}}}));
  return available;
}
function mean(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0}function median(xs){if(!xs.length)return 0;const a=[...xs].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function captainCounts(rows){const m=new Map();rows.forEach(r=>m.set(r.captain||'N/A',(m.get(r.captain||'N/A')||0)+1));return [...m].sort((a,b)=>b[1]-a[1])}
function renderKpis(rows){const pts=rows.map(r=>+r.gw_points||0);const top=[...rows].sort((a,b)=>(b.gw_points||0)-(a.gw_points||0))[0];const caps=captainCounts(rows);$('#kpis').innerHTML=[['Managers',fmt(rows.length),'tracked in selected league'],['Average GW',mean(pts).toFixed(1),`Median ${median(pts).toFixed(1)}`],['Top Score',fmt(top?.gw_points||0),top?.entry_name||'—'],['Top Captain',caps[0]?.[0]||'—',caps[0]?`${caps[0][1]} managers`:'—']].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div>`).join('')}
function renderTop(rows){const top=[...rows].sort((a,b)=>(b.gw_points||0)-(a.gw_points||0)).slice(0,10);$('#topPerformers').innerHTML=top.map((r,i)=>`<div class="rank-row manager-link" data-id="${r.entry_id}"><div class="rank-num">${i+1}</div><div><strong>${esc(r.entry_name)}</strong><small>${esc(r.player_name)}</small></div><span>${fmt(r.gw_points)} pts</span></div>`).join('')}
function renderCaptains(rows){const caps=captainCounts(rows).slice(0,8),max=caps[0]?.[1]||1;$('#captainBars').innerHTML=caps.map(([n,c])=>`<div class="bar-row"><div class="bar-label">${esc(n)}</div><div class="bar-track"><div class="bar-fill" style="width:${c/max*100}%"></div></div><div class="bar-value">${(c/rows.length*100).toFixed(1)}%</div></div>`).join('')}
function renderDistribution(rows){const vals=rows.map(r=>+r.gw_points||0),min=Math.min(...vals,0),max=Math.max(...vals,1),step=Math.max(5,Math.ceil((max-min)/12/5)*5),bins=[];for(let a=Math.floor(min/step)*step;a<=max;a+=step)bins.push({a,b:a+step-1,n:0});vals.forEach(v=>{const i=Math.min(bins.length-1,Math.floor((v-bins[0].a)/step));if(bins[i])bins[i].n++});const mx=Math.max(...bins.map(b=>b.n),1);$('#distribution').innerHTML=bins.map(b=>`<div class="hist-bar" style="height:${Math.max(4,b.n/mx*100)}%" data-label="${b.a}-${b.b}: ${b.n}"></div>`).join('');$('#distMeta').textContent=`${Math.min(...vals)}–${Math.max(...vals)} pts`}
function filteredManagers(input){const q=input.trim().toLowerCase();return (state.compact?.competitors||[]).filter(r=>!q||`${r.entry_name} ${r.player_name}`.toLowerCase().includes(q))}
function renderLeague(){let rows=filteredManagers($('#leagueSearch').value);const {key,dir}=state.sort;rows.sort((a,b)=>{const x=a[key]??'',y=b[key]??'';return typeof x==='number'?(x-y)*dir:String(x).localeCompare(String(y))*dir});$('#leagueBody').innerHTML=rows.map(r=>`<tr data-id="${r.entry_id}"><td>${fmt(r.league_rank)}</td><td><strong>${esc(r.entry_name)}</strong></td><td>${esc(r.player_name)}</td><td>${fmt(r.gw_points)}</td><td>${fmt(r.total_points)}</td><td><span class="pill">${esc(r.captain)}</span></td><td>${fmt(r.transfers_made)}</td></tr>`).join('')}
function renderManagerCards(){const rows=filteredManagers($('#managerSearch').value).sort((a,b)=>(a.league_rank||99999)-(b.league_rank||99999)).slice(0,300);$('#managerCards').innerHTML=rows.map(r=>`<div class="manager-card" data-id="${r.entry_id}"><strong>${esc(r.entry_name)}</strong><span>${esc(r.player_name)}</span><div class="manager-meta"><small>#${fmt(r.league_rank)}</small><small>${fmt(r.gw_points)} pts</small><small>${esc(r.captain)}</small></div></div>`).join('')}
async function ensureFull(){if(state.full)return state.full;$('#playerLoading').textContent='Loading full squad snapshot…';state.full=await getJson(`../data/gw${state.gw}_league${state.league}_data.json`);$('#playerLoading').textContent='';return state.full}
async function renderPlayers(){try{const full=await ensureFull(),rows=full.competitors||[],m=new Map();rows.forEach(c=>(c.squad||[]).forEach(p=>{const x=m.get(p.element)||{name:p.name,team:p.team,position:p.position,owned:0,captain:0,form:0,formN:0};x.owned++;if(p.is_captain)x.captain++;if(Number.isFinite(+p.form)){x.form+=+p.form;x.formN++}m.set(p.element,x)}));const q=$('#playerSearch').value.trim().toLowerCase();const arr=[...m.values()].filter(p=>!q||`${p.name} ${p.team}`.toLowerCase().includes(q)).sort((a,b)=>b.owned-a.owned);$('#playerBody').innerHTML=arr.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.team)}</td><td>${esc(p.position)}</td><td>${p.owned}</td><td>${(p.owned/rows.length*100).toFixed(1)}%</td><td>${p.captain}</td><td>${(p.captain/rows.length*100).toFixed(1)}%</td><td>${p.formN?(p.form/p.formN).toFixed(1):'—'}</td></tr>`).join('')}catch(e){$('#playerLoading').textContent=`Could not load full snapshot: ${e.message}`}}
async function openManager(id){try{const full=await ensureFull(),c=(full.competitors||[]).find(x=>String(x.entry_id)===String(id));if(!c)return;$('#dialogTitle').textContent=c.entry_name||`Entry ${id}`;$('#dialogSub').textContent=`${c.player_name||''} · League rank #${fmt(c.league_rank)}`;const squad=c.squad||[];$('#dialogContent').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>GW Points</span><strong>${fmt(c.gw_points)}</strong></div><div class="mini-kpi"><span>Total</span><strong>${fmt(c.total_points)}</strong></div><div class="mini-kpi"><span>Transfers</span><strong>${fmt(c.transfers_made)}</strong></div><div class="mini-kpi"><span>Squad Value</span><strong>${c.squad_cost?Number(c.squad_cost).toFixed(1):'—'}</strong></div></div><div class="squad-grid">${squad.map(p=>`<div class="squad-card ${p.is_captain?'captain':''}"><strong>${esc(p.name)}</strong><span>${esc(p.team)} · ${esc(p.position)} · £${Number(p.cost||0).toFixed(1)}m</span>${p.is_captain?'<em class="badge">Captain</em>':p.is_vice_captain?'<em class="badge">Vice</em>':''}</div>`).join('')}</div>`;$('#managerDialog').showModal()}catch(e){alert(`Manager detail unavailable: ${e.message}`)}}
async function load(){state.full=null;$('#statusText').textContent=`Loading league ${state.league}, GW${state.gw}…`;try{state.compact=await getJson(`../data/gw${state.gw}_league${state.league}_compact.json`);const rows=state.compact.competitors||[];renderKpis(rows);renderTop(rows);renderCaptains(rows);renderDistribution(rows);renderLeague();renderManagerCards();$('#playerBody').innerHTML='';$('#playerLoading').textContent='Open this tab to derive player intelligence from the full GW snapshot.';$('#statusText').textContent=`GW${state.gw} · ${fmt(rows.length)} managers · snapshot ${state.compact.fetched_at?new Date(state.compact.fetched_at).toLocaleString():'loaded'}`}catch(e){$('#statusText').textContent=`Dataset unavailable: ${e.message}`}}
async function init(){const available=await discover();const leagueSelect=$('#leagueSelect');leagueSelect.innerHTML=LEAGUES.map(l=>`<option value="${l}">${l}</option>`).join('');if(!available[state.league]?.length){state.league=LEAGUES.find(l=>available[l]?.length)||LEAGUES[0]}leagueSelect.value=state.league;const syncGw=()=>{const gws=available[state.league]||[];$('#gwSelect').innerHTML=gws.map(g=>`<option value="${g}">GW${g}</option>`).join('');state.gw=gws[gws.length-1]||1;$('#gwSelect').value=state.gw};syncGw();leagueSelect.addEventListener('change',()=>{state.league=+leagueSelect.value;syncGw();load()});$('#gwSelect').addEventListener('change',()=>{state.gw=+$('#gwSelect').value;load()});await load()}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.view}`).classList.add('active');state.view=b.dataset.view;$('#pageTitle').textContent=b.textContent;if(state.view==='players')renderPlayers()});
$('#leagueSearch').addEventListener('input',renderLeague);$('#managerSearch').addEventListener('input',renderManagerCards);$('#playerSearch').addEventListener('input',renderPlayers);document.addEventListener('click',e=>{const x=e.target.closest('[data-id]');if(x&&(x.closest('#leagueBody')||x.classList.contains('manager-card')||x.classList.contains('manager-link')))openManager(x.dataset.id)});$$('th[data-sort]').forEach(th=>th.addEventListener('click',()=>{const k=th.dataset.sort;if(state.sort.key===k)state.sort.dir*=-1;else state.sort={key:k,dir:1};renderLeague()}));$('#closeDialog').addEventListener('click',()=>$('#managerDialog').close());init();