const LEAGUES=[
  {id:19292,name:'LIGA KOPAK'},
  {id:58005,name:'LIGA FPL KK OLD BOYS'},
  {id:687126,name:'LIGA FPL MALAYSIA'},
  {id:131997,name:'OVERALL IFE'}
];
const GW_LABELS={1:'GW1 · Opening Weekend',2:'GW2',3:'GW3',4:'GW4',5:'GW5',6:'GW6',7:'GW7',8:'GW8',9:'GW9',10:'GW10',11:'GW11',12:'GW12',13:'GW13',14:'GW14',15:'GW15',16:'GW16',17:'GW17',18:'GW18',19:'GW19',20:'GW20',21:'GW21',22:'GW22',23:'GW23',24:'GW24',25:'GW25',26:'GW26',27:'GW27',28:'GW28',29:'GW29',30:'GW30',31:'GW31',32:'GW32',33:'GW33',34:'GW34',35:'GW35',36:'GW36',37:'GW37',38:'GW38 · Finale'};
const state={league:58005,gw:null,compact:null,full:null,available:{},sort:{key:'league_rank',dir:1},view:'overview',loaded:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('en-MY').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ago=d=>{const s=Math.floor((Date.now()-new Date(d).getTime())/1000);if(s<60)return'just now';if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;return`${Math.floor(s/86400)}d ago`};
const ELITE_THRESHOLD_PCT=5; // top 5% by overall_rank
async function getJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${path}`);return r.json()}
async function discover(){const a={};await Promise.all(LEAGUES.map(async l=>{const id=l.id;a[id]=[];for(let g=1;g<=5;g++){try{const r=await fetch(`/data/gw${g}_league${id}_compact.json`,{method:'HEAD',cache:'no-store'});if(r.ok)a[id].push(g);else break}catch{break}}}));return a}
const mean=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;const median=x=>{if(!x.length)return 0;const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function captainCounts(rows){const m=new Map();rows.forEach(r=>m.set(r.captain||'N/A',(m.get(r.captain||'N/A')||0)+1));return[...m].sort((a,b)=>b[1]-a[1])}
function delta(r){const cur=+r.league_rank||0,prev=+r.league_last_rank||0;return prev&&cur?prev-cur:0}function deltaHtml(r){const d=delta(r);return d?`<span class="delta ${d>0?'up':'down'}">${d>0?'▲':'▼'} ${Math.abs(d)}</span>`:'<span class="delta flat">—</span>'}
function leagueName(id){const l=LEAGUES.find(x=>x.id===id);return l?l.name:`League ${id}`}

// ── Overview ──
function renderKpis(rows){const pts=rows.map(r=>+r.gw_points||0),top=[...rows].sort((a,b)=>(b.gw_points||0)-(a.gw_points||0))[0],movers=rows.filter(r=>delta(r)>0).length;$('#kpis').innerHTML=[['Managers',fmt(rows.length),'selected league'],['Average GW',mean(pts).toFixed(1),`Median ${median(pts).toFixed(1)}`],['Top Score',fmt(top?.gw_points||0),top?.entry_name||'—'],['Rank Risers',fmt(movers),'improved rank']].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div>`).join('')}
function renderTop(rows){$('#topPerformers').innerHTML=[...rows].sort((a,b)=>(b.gw_points||0)-(a.gw_points||0)).slice(0,10).map((r,i)=>`<div class="rank-row manager-link" data-id="${r.entry_id}" style="animation-delay:${i*0.05}s"><div class="rank-num">${i+1}</div><div><strong>${esc(r.entry_name)}</strong><small>${esc(r.player_name)}</small></div><span>${fmt(r.gw_points)} pts</span></div>`).join('')}
function renderCaptains(rows){const caps=captainCounts(rows).slice(0,8),max=caps[0]?.[1]||1;$('#captainBars').innerHTML=caps.map(([n,c])=>`<div class="bar-row"><div class="bar-label">${esc(n)}</div><div class="bar-track"><div class="bar-fill" style="width:${c/max*100}%"></div></div><div class="bar-value">${(c/rows.length*100).toFixed(1)}%</div></div>`).join('')}
function renderDistribution(rows){const vals=rows.map(r=>+r.gw_points||0);if(!vals.length)return;const min=Math.min(...vals),max=Math.max(...vals),step=Math.max(5,Math.ceil((max-min||5)/12/5)*5),bins=[];for(let a=Math.floor(min/step)*step;a<=max;a+=step)bins.push({a,b:a+step-1,n:0});vals.forEach(v=>{const i=Math.min(bins.length-1,Math.floor((v-bins[0].a)/step));if(bins[i])bins[i].n++});const mx=Math.max(...bins.map(b=>b.n),1);$('#distribution').innerHTML=bins.map((b,i)=>`<div class="hist-bar" style="height:0;animation:growBar 0.6s ease-out ${i*0.08}s forwards" data-label="${b.a}-${b.b}: ${b.n}"></div>`).join('');$('#distMeta').textContent=`${min}–${max} pts`;setTimeout(()=>{$$('.hist-bar').forEach((el,i)=>{const h=bins[i].n/mx*100;el.style.height=`${Math.max(4,h)}%`})},50)}
function renderRankMovers(rows){const movers=[...rows].sort((a,b)=>Math.abs(delta(b))-Math.abs(delta(a))).slice(0,10);$('#rankMovers').innerHTML=movers.map(r=>`<div class="rank-row manager-link" data-id="${r.entry_id}"><div>${deltaHtml(r)}</div><div><strong>${esc(r.entry_name)}</strong><small>${esc(r.player_name)}</small></div><span>#${fmt(r.league_rank)}</span></div>`).join('')||'<div class="empty">No rank movement yet.</div>'}

// ── League Explorer ──
function filteredManagers(input){const q=input.trim().toLowerCase();return(state.compact?.competitors||[]).filter(r=>!q||`${r.entry_name} ${r.player_name}`.toLowerCase().includes(q))}
function renderLeague(){let rows=filteredManagers($('#leagueSearch').value);const{key,dir}=state.sort;rows.sort((a,b)=>{const x=a[key]??'',y=b[key]??'';return typeof x==='number'?(x-y)*dir:String(x).localeCompare(String(y))*dir});$('#leagueBody').innerHTML=rows.map(r=>`<tr data-id="${r.entry_id}"><td>${fmt(r.league_rank)}</td><td>${deltaHtml(r)}</td><td><strong>${esc(r.entry_name)}</strong></td><td>${esc(r.player_name)}</td><td>${fmt(r.gw_points)}</td><td>${fmt(r.total_points)}</td><td><span class="pill">${esc(r.captain)}</span></td><td>${fmt(r.transfers_made)}</td></tr>`).join('')}
function renderManagerCards(){const rows=filteredManagers($('#managerSearch').value).sort((a,b)=>(a.league_rank||99999)-(b.league_rank||99999)).slice(0,300);$('#managerCards').innerHTML=rows.map(r=>`<div class="manager-card" data-id="${r.entry_id}"><strong>${esc(r.entry_name)}</strong><span>${esc(r.player_name)}</span><div class="manager-meta"><small>#${fmt(r.league_rank)}</small><small>${fmt(r.gw_points)} pts</small><small>${esc(r.captain)}</small></div></div>`).join('')}

// ── Data helpers ──
async function ensureFull(){if(state.full)return state.full;state.full=await getJson(`/data/gw${state.gw}_league${state.league}_data.json`);return state.full}
function playerMap(rows){const m=new Map();rows.forEach(c=>(c.squad||[]).forEach(p=>{const x=m.get(p.element)||{id:p.element,name:p.name,team:p.team,position:p.position,owned:0,captain:0,vc:0,squad_cost:0,selected_by:p.selected_by||0,form:0,formN:0};x.owned++;if(p.is_captain)x.captain++;if(p.is_vice_captain)x.vc++;x.squad_cost+=p.cost||0;if(Number.isFinite(+p.form)){x.form+=+p.form;x.formN++}m.set(p.element,x)}));return m}

// ── Template XI ──
async function renderTemplate(){try{const rows=(await ensureFull()).competitors||[],arr=[...playerMap(rows).values()].sort((a,b)=>b.owned-a.owned);const byPos=p=>arr.filter(x=>x.position===p);const XI=[...byPos('GKP').slice(0,1),...byPos('DEF').slice(0,3),...byPos('MID').slice(0,4),...byPos('FWD').slice(0,3)];$('#templateXI').innerHTML=XI.map(p=>`<div class="template-card"><strong>${esc(p.name)}</strong><span>${esc(p.position)} · ${esc(p.team)}</span><small>${(p.owned/rows.length*100).toFixed(1)}% owned</small></div>`).join('')}catch{$('#templateXI').innerHTML='<div class="empty">Full snapshot unavailable.</div>'}}

// ── Player Intelligence ──
async function renderPlayers(){try{const rows=(await ensureFull()).competitors||[],q=$('#playerSearch').value.trim().toLowerCase(),arr=[...playerMap(rows).values()].filter(p=>!q||`${p.name} ${p.team}`.toLowerCase().includes(q)).sort((a,b)=>b.owned-a.owned);$('#playerBody').innerHTML=arr.map(p=>{const own=p.owned/rows.length*100,diff=own<10?'High':own<25?'Medium':'Template';return`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.team)}</td><td>${esc(p.position)}</td><td>${p.owned}</td><td>${own.toFixed(1)}%</td><td>${p.captain}</td><td>${(p.captain/rows.length*100).toFixed(1)}%</td><td><span class="pill">${diff}</span></td><td>${p.formN?(p.form/p.formN).toFixed(1):'—'}</td></tr>`}).join('');$('#playerLoading').textContent=''}catch(e){$('#playerLoading').textContent=`Could not load full snapshot: ${e.message}`}}

// ── Manager Selects ──
function populateManagerSelects(){const rows=[...(state.compact?.competitors||[])].sort((a,b)=>(a.league_rank||99999)-(b.league_rank||99999)),opts=rows.map(r=>`<option value="${r.entry_id}">#${r.league_rank} ${esc(r.entry_name)} — ${esc(r.player_name)}</option>`).join('');['compareA','compareB','myTeamSelect'].forEach(id=>$('#'+id).innerHTML=opts);if(rows[1])$('#compareB').value=rows[1].entry_id}

// ── Compare Managers ──
async function renderCompare(){try{const rows=(await ensureFull()).competitors||[],a=rows.find(x=>String(x.entry_id)===$('#compareA').value),b=rows.find(x=>String(x.entry_id)===$('#compareB').value);if(!a||!b)return;const sa=new Map((a.squad||[]).map(p=>[p.element,p])),sb=new Map((b.squad||[]).map(p=>[p.element,p]));const common=[...sa.keys()].filter(k=>sb.has(k)),ua=[...sa.values()].filter(p=>!sb.has(p.element)),ub=[...sb.values()].filter(p=>!sa.has(p.element));$('#compareResult').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>Squad overlap</span><strong>${common.length}/15</strong></div><div class="mini-kpi"><span>${esc(a.entry_name)} unique</span><strong>${ua.length}</strong></div><div class="mini-kpi"><span>${esc(b.entry_name)} unique</span><strong>${ub.length}</strong></div><div class="mini-kpi"><span>GW points gap</span><strong>${Math.abs((a.gw_points||0)-(b.gw_points||0))}</strong></div></div><div class="compare-grid"><div><h3>${esc(a.entry_name)}</h3>${ua.map(p=>`<span class="pick-chip">${esc(p.name)}</span>`).join('')||'No unique picks'}</div><div><h3>Shared ${common.length}</h3>${common.map(id=>`<span class="pick-chip shared">${esc(sa.get(id).name)}</span>`).join('')}</div><div><h3>${esc(b.entry_name)}</h3>${ub.map(p=>`<span class="pick-chip">${esc(p.name)}</span>`).join('')||'No unique picks'}</div></div>`}catch(e){$('#compareResult').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}

// ── Transfers & Chips ──
async function renderTransfers(){try{const rows=(await ensureFull()).competitors||[],moves=new Map(),chips=new Map();rows.forEach(c=>{(c.transfer_details||[]).forEach(t=>{const k=`${t.out} → ${t.in}`;moves.set(k,(moves.get(k)||0)+1)});(c.chips_used||[]).forEach(ch=>{const n=ch.name||ch.chip_name||'Chip';chips.set(n,(chips.get(n)||0)+1)})});$('#transferIntel').innerHTML=[...moves].sort((a,b)=>b[1]-a[1]).slice(0,15).map(([m,n])=>`<div class="rank-row"><div class="rank-num">${n}</div><div><strong>${esc(m)}</strong></div><span>${n} moves</span></div>`).join('')||'<div class="empty">No recorded transfers for this GW.</div>';$('#chipTracker').innerHTML=[...chips].sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<div class="rank-row"><div class="rank-num">${c}</div><div><strong>${esc(n)}</strong></div><span>${c} used</span></div>`).join('')||'<div class="empty">No chips used this GW.</div>';renderChipChart(chips,rows.length)}catch(e){$('#transferIntel').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderChipChart(chips,total){const entries=[...chips];if(!entries.length){$('#chipChart').innerHTML='';return}const colors={'bboost':'#43d986','3xc':'#68e7ff','wildcard':'#ffd166','freehit':'#ff7d87','Bench Boost':'#43d986','Triple Captain':'#68e7ff','Wildcard':'#ffd166','Free Hit':'#ff7d87'};$('#chipChart').innerHTML=`<div class="pie-legend">${entries.map(([n,c])=>`<span class="pie-legend-item"><span class="pie-dot" style="background:${colors[n]||'#80ffb2'}"></span>${esc(n)}: ${c} (${(c/total*100).toFixed(1)}%)</span>`).join('')}</div><div class="pie-track"><div class="pie-fills">${entries.map(([n,c],i)=>{const pct=c/total*100;const colorsArr=Object.values(colors);return`<div class="pie-seg" style="width:${pct}%;background:${colors[n]||colorsArr[i%colorsArr.length]};min-width:${pct>1?'4px':'0'}"></div>`}).join('')}</div></div>`}

// ── My Team vs League ──
async function renderMyTeam(){try{const rows=(await ensureFull()).competitors||[],me=rows.find(x=>String(x.entry_id)===$('#myTeamSelect').value);if(!me)return;const pm=playerMap(rows),mine=me.squad||[],diffs=mine.map(p=>({p,own:(pm.get(p.element)?.owned||0)/rows.length*100})).sort((a,b)=>a.own-b.own),similar=rows.filter(x=>x.entry_id!==me.entry_id).map(x=>{const ids=new Set((x.squad||[]).map(p=>p.element));return{x,n:mine.filter(p=>ids.has(p.element)).length}}).sort((a,b)=>b.n-a.n).slice(0,5);$('#myTeamResult').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>League rank</span><strong>#${fmt(me.league_rank)}</strong></div><div class="mini-kpi"><span>GW points</span><strong>${fmt(me.gw_points)}</strong></div><div class="mini-kpi"><span>Captain</span><strong>${esc(me.captain)}</strong></div><div class="mini-kpi"><span>Transfers</span><strong>${fmt(me.transfers_made)}</strong></div></div><div class="grid two"><div><h3>Your strongest differentials</h3>${diffs.slice(0,8).map(({p,own})=>`<div class="rank-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.team)} · ${esc(p.position)}</small></div><span>${own.toFixed(1)}%</span></div>`).join('')}</div><div><h3>Most similar managers</h3>${similar.map(({x,n})=>`<div class="rank-row manager-link" data-id="${x.entry_id}"><div><strong>${esc(x.entry_name)}</strong><small>${esc(x.player_name)}</small></div><span>${n}/15 shared</span></div>`).join('')}</div></div>`}catch(e){$('#myTeamResult').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}

// ── Manager Detail ──
async function openManager(id){try{const c=((await ensureFull()).competitors||[]).find(x=>String(x.entry_id)===String(id));if(!c)return;$('#dialogTitle').textContent=c.entry_name||`Entry ${id}`;$('#dialogSub').textContent=`${c.player_name||''} · League rank #${fmt(c.league_rank)}`;$('#dialogContent').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>GW Points</span><strong>${fmt(c.gw_points)}</strong></div><div class="mini-kpi"><span>Total</span><strong>${fmt(c.total_points)}</strong></div><div class="mini-kpi"><span>Transfers</span><strong>${fmt(c.transfers_made)}</strong></div><div class="mini-kpi"><span>Squad Value</span><strong>${c.squad_cost?Number(c.squad_cost).toFixed(1):'—'}</strong></div></div><div class="squad-grid">${(c.squad||[]).map(p=>`<div class="squad-card ${p.is_captain?'captain':''}"><strong>${esc(p.name)}</strong><span>${esc(p.team)} · ${esc(p.position)} · £${Number(p.cost||0).toFixed(1)}m${p.selected_by?` · ${p.selected_by}%`:''}</span>${p.is_captain?'<em class="badge">Captain</em>':p.is_vice_captain?'<em class="badge">Vice</em>':''}</div>`).join('')}</div>`;$('#managerDialog').showModal()}catch(e){alert(`Manager detail unavailable: ${e.message}`)}}

// ── Elite Tracker ──
async function renderElite(){try{const rows=(await ensureFull()).competitors||[];if(!rows.length){$('#eliteContent').innerHTML='<div class="empty">No data</div>';return}
// Determine top 5% threshold by overall_rank
const sorted=[...rows].sort((a,b)=>(a.overall_rank||99999999)-(b.overall_rank||99999999));
const eliteCount=Math.max(1,Math.ceil(rows.length*ELITE_THRESHOLD_PCT/100));
const elite=sorted.slice(0,eliteCount);
const thresholdRank=elite[elite.length-1].overall_rank||99999999;
const pm=playerMap(rows);
const elitePlayerMap=playerMap(elite);
// Unique picks among elite
const allElitePicks=new Map();elite.forEach(c=>(c.squad||[]).forEach(p=>{const k=p.element;if(!allElitePicks.has(k))allElitePicks.set(k,{...p,elite_owned:0,elite_captain:0});const x=allElitePicks.get(k);x.elite_owned++;if(p.is_captain)x.elite_captain++}));
const elitePicksSorted=[...allElitePicks.values()].sort((a,b)=>b.elite_owned-a.elite_owned);
// Transfers IN among elite
const eliteTransfers=new Map();elite.forEach(c=>{(c.transfer_details||[]).forEach(t=>{const k=`${t.out}→${t.in}`;eliteTransfers.set(k,(eliteTransfers.get(k)||0)+1)})});
// Chips used by elite
const eliteChips=new Map();elite.forEach(c=>{(c.chips_used||[]).forEach(ch=>{const n=ch.name||ch.chip_name||'Chip';eliteChips.set(n,(eliteChips.get(n)||0)+1)})});
// Squad cost stats
const costs=elite.map(c=>c.squad_cost||0).filter(c=>c>0);
const avgCost=mean(costs);
const minCost=Math.min(...costs);
const maxCost=Math.max(...costs);

// Build HTML
let html=`
<div class="hero-strip" style="margin-bottom:16px"><div><span class="hero-kicker">ELITE WATCH</span><h2>Top ${ELITE_THRESHOLD_PCT}% — ${eliteCount} managers</h2><p>Overall rank ≤ ${fmt(thresholdRank)} · Avg squad cost £${fmt(avgCost)}m (${fmt(minCost)}–${fmt(maxCost)})</p></div></div>
<div class="mini-kpis elite-mini-kpis">
  <div class="mini-kpi"><span>Avg GW Points</span><strong>${mean(elite.map(r=>+r.gw_points||0)).toFixed(1)}</strong></div>
  <div class="mini-kpi"><span>Avg Total</span><strong>${mean(elite.map(r=>+r.total_points||0)).toFixed(1)}</strong></div>
  <div class="mini-kpi"><span>Avg Squad Value</span><strong>£${avgCost.toFixed(1)}m</strong></div>
  <div class="mini-kpi"><span>Top Captain</span><strong>${esc(captainCounts(elite)[0]?.[0]||'—')}</strong></div>
</div>
<div class="grid two">
  <article class="panel"><div class="panel-head"><div><span class="panel-kicker">ELITE</span><h2>Elite Managers</h2></div><span class="panel-tag">TOP ${eliteCount}</span></div>
  <div class="elite-manager-list">${elite.map((r,i)=>`<div class="rank-row manager-link" data-id="${r.entry_id}"><div class="rank-num">${i+1}</div><div><strong>${esc(r.entry_name)}</strong><small>${esc(r.player_name)}</small></div><span class="elite-meta">#${fmt(r.overall_rank)} · ${fmt(r.gw_points)}pts</span></div>`).join('')}</div></article>
  <article class="panel"><div class="panel-head"><div><span class="panel-kicker">ELITE META</span><h2>Most Owned by Elite</h2></div><span class="panel-tag">TOP 15</span></div>
  <div class="elite-picks-list">${elitePicksSorted.slice(0,15).map(p=>{const ownPct=(p.elite_owned/eliteCount*100).toFixed(1);const leagueOwnPct=((pm.get(p.element)?.owned||0)/rows.length*100).toFixed(1);const diff=ownPct-leagueOwnPct;const diffLabel=diff>5?'🔥':diff<-5?'❄️':'';return`<div class="elite-pick-row"><div class="elite-pick-info"><strong>${esc(p.name)}</strong><span>${esc(p.position)} · ${esc(p.team)}</span></div><div class="elite-pick-stats"><span class="pill">${ownPct}%</span>${diffLabel?`<span class="pill diff-pill">${diffLabel} ${diff>0?'+':''}${diff.toFixed(1)}% vs league</span>`:''}</div></div>`}).join('')}</div></article>
</div>
<article class="panel"><div class="panel-head"><div><span class="panel-kicker">ELITE SQUADS</span><h2>Elite Lineup Comparison</h2></div><span class="panel-tag">PLAYER GRID</span></div>
<div class="elite-grid-wrap"><table class="elite-grid"><thead><tr><th>Player</th>${elite.slice(0,20).map(r=>`<th title="${esc(r.entry_name)}">${esc(r.entry_name.slice(0,8))}</th>`).join('')}<th>Own%</th></tr></thead><tbody>${elitePicksSorted.slice(0,20).map(p=>{const ownPct=(p.elite_owned/eliteCount*100).toFixed(1);return`<tr><td class="elite-player-name"><strong>${esc(p.name)}</strong><small>${esc(p.team)}</small></td>${elite.slice(0,20).map(c=>{const found=c.squad?.find(sp=>sp.element===p.element);if(!found)return'<td class="elite-cell empty"></td>';const cls=found.is_captain?'captain':found.is_vice_captain?'vice':'';return`<td class="elite-cell ${cls}">${found.is_captain?'C':found.is_vice_captain?'V':'✓'}</td>`}).join('')}<td><span class="pill">${ownPct}%</span></td></tr>`}).join('')}</tbody></table></div></article>
`;if(eliteTransfers.size>0){html+=`<article class="panel"><div class="panel-head"><div><span class="panel-kicker">ELITE MOVES</span><h2>Elite Transfer Activity</h2></div><span class="panel-tag">TRANSFERS</span></div><div id="eliteTransferList">${[...eliteTransfers].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([m,n])=>`<div class="rank-row"><div class="rank-num">${n}</div><div><strong>${esc(m)}</strong></div><span>${n} moves</span></div>`).join('')||'<div class="empty">No transfers</div>'}</div></article>`}if(eliteChips.size>0){html+=`<article class="panel"><div class="panel-head"><div><span class="panel-kicker">ELITE CHIPS</span><h2>Chip Usage Among Elite</h2></div><span class="panel-tag">CHIPS</span></div><div class="chip-bar-list">${[...eliteChips].sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<div class="bar-row"><div class="bar-label">${esc(n)}</div><div class="bar-track"><div class="bar-fill" style="width:${c/eliteCount*100}%"></div></div><div class="bar-value">${(c/eliteCount*100).toFixed(1)}%</div></div>`).join('')}</div></article>`}
$('#eliteContent').innerHTML=html}catch(e){$('#eliteContent').innerHTML=`<div class="empty">Elite data unavailable: ${esc(e.message)}</div>`}}

// ── Analytics: Charts & Graphs ──
async function renderAnalytics(){try{const rows=(await ensureFull()).competitors||[];if(!rows.length)return;const pm=playerMap(rows);
// Squad cost distribution
const costs=rows.map(r=>r.squad_cost||0).filter(c=>c>0);const cMin=Math.min(...costs),cMax=Math.max(...costs),cStep=Math.max(1,Math.ceil((cMax-cMin||5)/10/1)*1);const cBins=[];for(let a=Math.floor(cMin/cStep)*cStep;a<=cMax;a+=cStep)cBins.push({a,b:a+cStep-1,n:0});costs.forEach(v=>{const i=Math.min(cBins.length-1,Math.floor((v-cBins[0].a)/cStep));if(cBins[i])cBins[i].n++});const cMx=Math.max(...cBins.map(b=>b.n),1);
let html=`
<div class="hero-strip" style="margin-bottom:16px"><div><span class="hero-kicker">ANALYTICS</span><h2>League Data Visualizations</h2></div></div>
<div class="grid two">
  <article class="panel"><div class="panel-head"><div><span class="panel-kicker">VALUE</span><h2>Squad Cost Distribution</h2></div><span class="panel-tag">£${fmt(cMin)}m–£${fmt(cMax)}m</span></div><div class="chart-bar-container">${cBins.map((b,i)=>`<div class="chart-bar-col"><div class="chart-bar" style="height:${Math.max(4,b.n/cMx*100)}%" data-label="£${b.a}–${b.b}m: ${b.n}"></div><span class="chart-bar-label">£${b.a}</span></div>`).join('')}</div></article>
  <article class="panel"><div class="panel-head"><div><span class="panel-kicker">POSITIONS</span><h2>Formation Distribution</h2></div><span class="panel-tag">TOP 5</span></div><div class="formation-list">${formationChart(rows)}</div></article>
</div>
<article class="panel"><div class="panel-head"><div><span class="panel-kicker">OWNERSHIP</span><h2>Ownership Saturation</h2></div><span class="panel-tag">PLAYERS BY LEAGUE OWNERSHIP %</span></div><div class="ownership-bars">${ownershipChart(rows,pm)}</div></article>
`;
$('#analyticsContent').innerHTML=html}catch(e){$('#analyticsContent').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function formationChart(rows){const fm=new Map();rows.forEach(r=>{const sq=r.squad||[];if(sq.length<11)return;const cnt={};for(let i=0;i<11;i++){const p=sq[i];cnt[p.position]=(cnt[p.position]||0)+1}const k=(cnt.GKP||0)+'-'+(cnt.DEF||0)+'-'+(cnt.MID||0)+'-'+(cnt.FWD||0);fm.set(k,(fm.get(k)||0)+1)});const sorted=[...fm].sort((a,b)=>b[1]-a[1]).slice(0,8);const mx=Math.max(...sorted.map(([,n])=>n),1);return sorted.map(([f,n])=>`<div class="bar-row"><div class="bar-label">${f}</div><div class="bar-track"><div class="bar-fill" style="width:${n/mx*100}%"></div></div><div class="bar-value">${n} (${(n/rows.length*100).toFixed(1)}%)</div></div>`).join('')||'<div class="empty">No formation data</div>'}
function ownershipChart(rows,pm){const arr=[...pm.values()].sort((a,b)=>b.owned-a.owned).slice(0,20);const mx=arr[0]?.owned||1;return arr.map(p=>{const pct=(p.owned/rows.length*100).toFixed(1);return`<div class="bar-row"><div class="bar-label">${esc(p.name)}</div><div class="bar-track"><div class="bar-fill" style="width:${p.owned/mx*100}%"></div></div><div class="bar-value">${p.owned} (${pct}%)</div></div>`}).join('')}

// ── Load ──
async function load(){state.full=null;const lname=leagueName(state.league);$('#statusText').textContent=`Loading ${lname} · GW${state.gw}`;$('#pageTitle').textContent=`${lname} · GW${state.gw}`;try{state.compact=await getJson(`/data/gw${state.gw}_league${state.league}_compact.json`);const rows=state.compact.competitors||[];renderKpis(rows);renderTop(rows);renderCaptains(rows);renderDistribution(rows);renderRankMovers(rows);renderLeague();renderManagerCards();populateManagerSelects();$('#playerBody').innerHTML='';$('#playerLoading').textContent='Open this tab to derive player intelligence from the full GW snapshot.';$('#templateXI').innerHTML='<div class="empty">Loading template…</div>';renderTemplate();const fetched=state.compact.fetched_at?new Date(state.compact.fetched_at):null;$('#statusText').innerHTML=`${lname} · GW${state.gw} · ${fmt(rows.length)} managers ${fetched?`<span class="freshness-badge">${ago(fetched)}</span>`:''}`;if(state.view==='compare')renderCompare();if(state.view==='transfers')renderTransfers();if(state.view==='myteam')renderMyTeam();if(state.view==='elite')renderElite();if(state.view==='analytics')renderAnalytics()}catch(e){$('#statusText').textContent=`Dataset unavailable: ${e.message}`}}

// ── Init ──
async function init(){state.available=await discover();const ls=$('#leagueSelect');ls.innerHTML=LEAGUES.map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('');if(!state.available[state.league]?.length)state.league=LEAGUES.find(l=>state.available[l.id]?.length)?.id||LEAGUES[0].id;ls.value=state.league;const sync=()=>{const g=state.available[state.league]||[];$('#gwSelect').innerHTML=g.map(x=>`<option value="${x}">${GW_LABELS[x]||`GW${x}`}</option>`).join('');state.gw=g[g.length-1]||1;$('#gwSelect').value=state.gw};sync();ls.addEventListener('change',()=>{state.league=+ls.value;sync();load()});$('#gwSelect').addEventListener('change',()=>{state.gw=+$('#gwSelect').value;load()});await load()}

// ── Navigation ──
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.view}`).classList.add('active');state.view=b.dataset.view;$('#pageTitle').textContent=b.textContent;if(state.view==='players')renderPlayers();if(state.view==='compare')renderCompare();if(state.view==='transfers')renderTransfers();if(state.view==='myteam')renderMyTeam();if(state.view==='elite')renderElite();if(state.view==='analytics')renderAnalytics()});
$('#leagueSearch').addEventListener('input',renderLeague);$('#managerSearch').addEventListener('input',renderManagerCards);$('#playerSearch').addEventListener('input',renderPlayers);$('#compareA').addEventListener('change',renderCompare);$('#compareB').addEventListener('change',renderCompare);$('#myTeamSelect').addEventListener('change',renderMyTeam);document.addEventListener('click',e=>{const x=e.target.closest('[data-id]');if(x&&(x.closest('#leagueBody')||x.classList.contains('manager-card')||x.classList.contains('manager-link')||x.closest('.elite-manager-list')))openManager(x.dataset.id)});$$('th[data-sort]').forEach(th=>th.addEventListener('click',()=>{const k=th.dataset.sort;if(state.sort.key===k)state.sort.dir*=-1;else state.sort={key:k,dir:1};renderLeague()}));$('#closeDialog').addEventListener('click',()=>$('#managerDialog').close());init();