const LEAGUES=[19292,58005,687126,131997];
const state={league:58005,gw:null,compact:null,full:null,available:{},sort:{key:'league_rank',dir:1},view:'overview'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('en-MY').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function getJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${path}`);return r.json()}
async function discover(){const a={};await Promise.all(LEAGUES.map(async l=>{a[l]=[];for(let g=1;g<=38;g++){try{const r=await fetch(`../data/gw${g}_league${l}_compact.json`,{method:'HEAD',cache:'no-store'});if(r.ok)a[l].push(g)}catch{}}}));return a}
const mean=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;const median=x=>{if(!x.length)return 0;const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function captainCounts(rows){const m=new Map();rows.forEach(r=>m.set(r.captain||'N/A',(m.get(r.captain||'N/A')||0)+1));return [...m].sort((a,b)=>b[1]-a[1])}
function delta(r){const cur=+r.league_rank||0,prev=+r.league_last_rank||0;return prev&&cur?prev-cur:0}function deltaHtml(r){const d=delta(r);return d?`<span class="delta ${d>0?'up':'down'}">${d>0?'▲':'▼'} ${Math.abs(d)}</span>`:'<span class="delta flat">—</span>'}
function renderKpis(rows){const pts=rows.map(r=>+r.gw_points||0),top=[...rows].sort((a,b)=>(b.gw_points||0)-(a.gw_points||0))[0],movers=rows.filter(r=>delta(r)>0).length;$('#kpis').innerHTML=[['Managers',fmt(rows.length),'selected league'],['Average GW',mean(pts).toFixed(1),`Median ${median(pts).toFixed(1)}`],['Top Score',fmt(top?.gw_points||0),top?.entry_name||'—'],['Rank Risers',fmt(movers),'improved rank']].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div>`).join('')}
function renderTop(rows){$('#topPerformers').innerHTML=[...rows].sort((a,b)=>(b.gw_points||0)-(a.gw_points||0)).slice(0,10).map((r,i)=>`<div class="rank-row manager-link" data-id="${r.entry_id}"><div class="rank-num">${i+1}</div><div><strong>${esc(r.entry_name)}</strong><small>${esc(r.player_name)}</small></div><span>${fmt(r.gw_points)} pts</span></div>`).join('')}
function renderCaptains(rows){const caps=captainCounts(rows).slice(0,8),max=caps[0]?.[1]||1;$('#captainBars').innerHTML=caps.map(([n,c])=>`<div class="bar-row"><div class="bar-label">${esc(n)}</div><div class="bar-track"><div class="bar-fill" style="width:${c/max*100}%"></div></div><div class="bar-value">${(c/rows.length*100).toFixed(1)}%</div></div>`).join('')}
function renderDistribution(rows){const vals=rows.map(r=>+r.gw_points||0);if(!vals.length)return;const min=Math.min(...vals),max=Math.max(...vals),step=Math.max(5,Math.ceil((max-min||5)/12/5)*5),bins=[];for(let a=Math.floor(min/step)*step;a<=max;a+=step)bins.push({a,b:a+step-1,n:0});vals.forEach(v=>{const i=Math.min(bins.length-1,Math.floor((v-bins[0].a)/step));if(bins[i])bins[i].n++});const mx=Math.max(...bins.map(b=>b.n),1);$('#distribution').innerHTML=bins.map(b=>`<div class="hist-bar" style="height:${Math.max(4,b.n/mx*100)}%" data-label="${b.a}-${b.b}: ${b.n}"></div>`).join('');$('#distMeta').textContent=`${min}–${max} pts`}
function renderRankMovers(rows){const movers=[...rows].sort((a,b)=>Math.abs(delta(b))-Math.abs(delta(a))).slice(0,10);$('#rankMovers').innerHTML=movers.map(r=>`<div class="rank-row manager-link" data-id="${r.entry_id}"><div>${deltaHtml(r)}</div><div><strong>${esc(r.entry_name)}</strong><small>${esc(r.player_name)}</small></div><span>#${fmt(r.league_rank)}</span></div>`).join('')||'<div class="empty">No rank movement yet.</div>'}
function filteredManagers(input){const q=input.trim().toLowerCase();return (state.compact?.competitors||[]).filter(r=>!q||`${r.entry_name} ${r.player_name}`.toLowerCase().includes(q))}
function renderLeague(){let rows=filteredManagers($('#leagueSearch').value);const {key,dir}=state.sort;rows.sort((a,b)=>{const x=a[key]??'',y=b[key]??'';return typeof x==='number'?(x-y)*dir:String(x).localeCompare(String(y))*dir});$('#leagueBody').innerHTML=rows.map(r=>`<tr data-id="${r.entry_id}"><td>${fmt(r.league_rank)}</td><td>${deltaHtml(r)}</td><td><strong>${esc(r.entry_name)}</strong></td><td>${esc(r.player_name)}</td><td>${fmt(r.gw_points)}</td><td>${fmt(r.total_points)}</td><td><span class="pill">${esc(r.captain)}</span></td><td>${fmt(r.transfers_made)}</td></tr>`).join('')}
function renderManagerCards(){const rows=filteredManagers($('#managerSearch').value).sort((a,b)=>(a.league_rank||99999)-(b.league_rank||99999)).slice(0,300);$('#managerCards').innerHTML=rows.map(r=>`<div class="manager-card" data-id="${r.entry_id}"><strong>${esc(r.entry_name)}</strong><span>${esc(r.player_name)}</span><div class="manager-meta"><small>#${fmt(r.league_rank)}</small><small>${fmt(r.gw_points)} pts</small><small>${esc(r.captain)}</small></div></div>`).join('')}
async function ensureFull(){if(state.full)return state.full;state.full=await getJson(`../data/gw${state.gw}_league${state.league}_data.json`);return state.full}
function playerMap(rows){const m=new Map();rows.forEach(c=>(c.squad||[]).forEach(p=>{const x=m.get(p.element)||{id:p.element,name:p.name,team:p.team,position:p.position,owned:0,captain:0,form:0,formN:0};x.owned++;if(p.is_captain)x.captain++;if(Number.isFinite(+p.form)){x.form+=+p.form;x.formN++}m.set(p.element,x)}));return m}
async function renderTemplate(){try{const rows=(await ensureFull()).competitors||[],arr=[...playerMap(rows).values()].sort((a,b)=>b.owned-a.owned);const byPos=p=>arr.filter(x=>x.position===p);const XI=[...byPos('GKP').slice(0,1),...byPos('DEF').slice(0,3),...byPos('MID').slice(0,4),...byPos('FWD').slice(0,3)];$('#templateXI').innerHTML=XI.map(p=>`<div class="template-card"><strong>${esc(p.name)}</strong><span>${esc(p.position)} · ${esc(p.team)}</span><small>${(p.owned/rows.length*100).toFixed(1)}% owned</small></div>`).join('')}catch{$('#templateXI').innerHTML='<div class="empty">Full snapshot unavailable.</div>'}}
async function renderPlayers(){try{const rows=(await ensureFull()).competitors||[],q=$('#playerSearch').value.trim().toLowerCase(),arr=[...playerMap(rows).values()].filter(p=>!q||`${p.name} ${p.team}`.toLowerCase().includes(q)).sort((a,b)=>b.owned-a.owned);$('#playerBody').innerHTML=arr.map(p=>{const own=p.owned/rows.length*100,diff=own<10?'High':own<25?'Medium':'Template';return `<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.team)}</td><td>${esc(p.position)}</td><td>${p.owned}</td><td>${own.toFixed(1)}%</td><td>${p.captain}</td><td>${(p.captain/rows.length*100).toFixed(1)}%</td><td><span class="pill">${diff}</span></td><td>${p.formN?(p.form/p.formN).toFixed(1):'—'}</td></tr>`}).join('');$('#playerLoading').textContent=''}catch(e){$('#playerLoading').textContent=`Could not load full snapshot: ${e.message}`}}
function populateManagerSelects(){const rows=[...(state.compact?.competitors||[])].sort((a,b)=>(a.league_rank||99999)-(b.league_rank||99999)),opts=rows.map(r=>`<option value="${r.entry_id}">#${r.league_rank} ${esc(r.entry_name)} — ${esc(r.player_name)}</option>`).join('');['compareA','compareB','myTeamSelect'].forEach(id=>$('#'+id).innerHTML=opts);if(rows[1])$('#compareB').value=rows[1].entry_id}
async function renderCompare(){try{const rows=(await ensureFull()).competitors||[],a=rows.find(x=>String(x.entry_id)===$('#compareA').value),b=rows.find(x=>String(x.entry_id)===$('#compareB').value);if(!a||!b)return;const sa=new Map((a.squad||[]).map(p=>[p.element,p])),sb=new Map((b.squad||[]).map(p=>[p.element,p]));const common=[...sa.keys()].filter(k=>sb.has(k)),ua=[...sa.values()].filter(p=>!sb.has(p.element)),ub=[...sb.values()].filter(p=>!sa.has(p.element));$('#compareResult').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>Squad overlap</span><strong>${common.length}/15</strong></div><div class="mini-kpi"><span>${esc(a.entry_name)} unique</span><strong>${ua.length}</strong></div><div class="mini-kpi"><span>${esc(b.entry_name)} unique</span><strong>${ub.length}</strong></div><div class="mini-kpi"><span>GW points gap</span><strong>${Math.abs((a.gw_points||0)-(b.gw_points||0))}</strong></div></div><div class="compare-grid"><div><h3>${esc(a.entry_name)}</h3>${ua.map(p=>`<span class="pick-chip">${esc(p.name)}</span>`).join('')||'No unique picks'}</div><div><h3>Shared ${common.length}</h3>${common.map(id=>`<span class="pick-chip shared">${esc(sa.get(id).name)}</span>`).join('')}</div><div><h3>${esc(b.entry_name)}</h3>${ub.map(p=>`<span class="pick-chip">${esc(p.name)}</span>`).join('')||'No unique picks'}</div></div>`}catch(e){$('#compareResult').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function renderTransfers(){try{const rows=(await ensureFull()).competitors||[],moves=new Map(),chips=new Map();rows.forEach(c=>{(c.transfer_details||[]).forEach(t=>{const k=`${t.out} → ${t.in}`;moves.set(k,(moves.get(k)||0)+1)});(c.chips_used||[]).forEach(ch=>{const n=ch.name||ch.chip_name||'Chip';chips.set(n,(chips.get(n)||0)+1)})});$('#transferIntel').innerHTML=[...moves].sort((a,b)=>b[1]-a[1]).slice(0,15).map(([m,n])=>`<div class="rank-row"><div class="rank-num">${n}</div><div><strong>${esc(m)}</strong></div><span>${n} moves</span></div>`).join('')||'<div class="empty">No recorded transfers for this GW.</div>';$('#chipTracker').innerHTML=[...chips].sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<div class="rank-row"><div class="rank-num">${c}</div><div><strong>${esc(n)}</strong></div><span>${c} used</span></div>`).join('')||'<div class="empty">No chips used this GW.</div>'}catch(e){$('#transferIntel').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function renderMyTeam(){try{const rows=(await ensureFull()).competitors||[],me=rows.find(x=>String(x.entry_id)===$('#myTeamSelect').value);if(!me)return;const pm=playerMap(rows),mine=me.squad||[],diffs=mine.map(p=>({p,own:(pm.get(p.element)?.owned||0)/rows.length*100})).sort((a,b)=>a.own-b.own),similar=rows.filter(x=>x.entry_id!==me.entry_id).map(x=>{const ids=new Set((x.squad||[]).map(p=>p.element));return {x,n:mine.filter(p=>ids.has(p.element)).length}}).sort((a,b)=>b.n-a.n).slice(0,5);$('#myTeamResult').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>League rank</span><strong>#${fmt(me.league_rank)}</strong></div><div class="mini-kpi"><span>GW points</span><strong>${fmt(me.gw_points)}</strong></div><div class="mini-kpi"><span>Captain</span><strong>${esc(me.captain)}</strong></div><div class="mini-kpi"><span>Transfers</span><strong>${fmt(me.transfers_made)}</strong></div></div><div class="grid two"><div><h3>Your strongest differentials</h3>${diffs.slice(0,8).map(({p,own})=>`<div class="rank-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.team)} · ${esc(p.position)}</small></div><span>${own.toFixed(1)}%</span></div>`).join('')}</div><div><h3>Most similar managers</h3>${similar.map(({x,n})=>`<div class="rank-row manager-link" data-id="${x.entry_id}"><div><strong>${esc(x.entry_name)}</strong><small>${esc(x.player_name)}</small></div><span>${n}/15 shared</span></div>`).join('')}</div></div>`}catch(e){$('#myTeamResult').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function openManager(id){try{const c=((await ensureFull()).competitors||[]).find(x=>String(x.entry_id)===String(id));if(!c)return;$('#dialogTitle').textContent=c.entry_name||`Entry ${id}`;$('#dialogSub').textContent=`${c.player_name||''} · League rank #${fmt(c.league_rank)}`;$('#dialogContent').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>GW Points</span><strong>${fmt(c.gw_points)}</strong></div><div class="mini-kpi"><span>Total</span><strong>${fmt(c.total_points)}</strong></div><div class="mini-kpi"><span>Transfers</span><strong>${fmt(c.transfers_made)}</strong></div><div class="mini-kpi"><span>Squad Value</span><strong>${c.squad_cost?Number(c.squad_cost).toFixed(1):'—'}</strong></div></div><div class="squad-grid">${(c.squad||[]).map(p=>`<div class="squad-card ${p.is_captain?'captain':''}"><strong>${esc(p.name)}</strong><span>${esc(p.team)} · ${esc(p.position)} · £${Number(p.cost||0).toFixed(1)}m</span>${p.is_captain?'<em class="badge">Captain</em>':p.is_vice_captain?'<em class="badge">Vice</em>':''}</div>`).join('')}</div>`;$('#managerDialog').showModal()}catch(e){alert(`Manager detail unavailable: ${e.message}`)}}
async function load(){state.full=null;$('#statusText').textContent=`Loading league ${state.league}, GW${state.gw}…`;try{state.compact=await getJson(`../data/gw${state.gw}_league${state.league}_compact.json`);const rows=state.compact.competitors||[];renderKpis(rows);renderTop(rows);renderCaptains(rows);renderDistribution(rows);renderRankMovers(rows);renderLeague();renderManagerCards();populateManagerSelects();$('#playerBody').innerHTML='';$('#playerLoading').textContent='Open this tab to derive player intelligence from the full GW snapshot.';$('#templateXI').innerHTML='<div class="empty">Loading template…</div>';renderTemplate();$('#statusText').textContent=`GW${state.gw} · ${fmt(rows.length)} managers · ${state.compact.fetched_at?new Date(state.compact.fetched_at).toLocaleString():'loaded'}`;if(state.view==='compare')renderCompare();if(state.view==='transfers')renderTransfers();if(state.view==='myteam')renderMyTeam()}catch(e){$('#statusText').textContent=`Dataset unavailable: ${e.message}`}}
async function init(){state.available=await discover();const ls=$('#leagueSelect');ls.innerHTML=LEAGUES.map(l=>`<option value="${l}">${l}</option>`).join('');if(!state.available[state.league]?.length)state.league=LEAGUES.find(l=>state.available[l]?.length)||LEAGUES[0];ls.value=state.league;const sync=()=>{const g=state.available[state.league]||[];$('#gwSelect').innerHTML=g.map(x=>`<option value="${x}">GW${x}</option>`).join('');state.gw=g[g.length-1]||1;$('#gwSelect').value=state.gw};sync();ls.addEventListener('change',()=>{state.league=+ls.value;sync();load()});$('#gwSelect').addEventListener('change',()=>{state.gw=+$('#gwSelect').value;load()});await load()}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.view}`).classList.add('active');state.view=b.dataset.view;$('#pageTitle').textContent=b.textContent;if(state.view==='players')renderPlayers();if(state.view==='compare')renderCompare();if(state.view==='transfers')renderTransfers();if(state.view==='myteam')renderMyTeam()});
$('#leagueSearch').addEventListener('input',renderLeague);$('#managerSearch').addEventListener('input',renderManagerCards);$('#playerSearch').addEventListener('input',renderPlayers);$('#compareA').addEventListener('change',renderCompare);$('#compareB').addEventListener('change',renderCompare);$('#myTeamSelect').addEventListener('change',renderMyTeam);document.addEventListener('click',e=>{const x=e.target.closest('[data-id]');if(x&&(x.closest('#leagueBody')||x.classList.contains('manager-card')||x.classList.contains('manager-link')))openManager(x.dataset.id)});$$('th[data-sort]').forEach(th=>th.addEventListener('click',()=>{const k=th.dataset.sort;if(state.sort.key===k)state.sort.dir*=-1;else state.sort={key:k,dir:1};renderLeague()}));$('#closeDialog').addEventListener('click',()=>$('#managerDialog').close());init();