import Link from "next/link";
import { ArrowLeft, BrainCircuit, CheckCircle2, Clock3, Database, Lightbulb, ShieldAlert, Trophy } from "lucide-react";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { getJournalEntry } from "@/lib/journal";

export default async function JournalGameweekPage({ params }: { params: Promise<{ season: string; gameweek: string }> }) {
  const { season, gameweek: value } = await params; const gameweek = Number(value); const entry = await getJournalEntry(season, gameweek);
  const starters = entry.outcome.squad.filter((player) => player.multiplier > 0); const bench = entry.outcome.squad.filter((player) => player.multiplier === 0);
  return <div className="page-stack journal-detail">
    <Link href="/journal" className="journal-back"><ArrowLeft size={14} /> Season timeline</Link>
    <PageHeader eyebrow={`${season} · GAMEWEEK ${gameweek}`} title={`GW${gameweek} Review`} description="Decision context, final outcome and durable lessons from this gameweek." updated={new Date(entry.generated_at).toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur" })} />
    <section className="journal-detail-hero"><div><span>{entry.summary.phase ?? "SEASON START"}</span><h2>{entry.summary.gw_points} points</h2><p>{entry.summary.points_vs_reference > 0 ? "+" : ""}{entry.summary.points_vs_reference} versus league reference · Captain {entry.summary.captain}</p></div><div className={entry.quality.status === "valid" ? "journal-quality valid" : "journal-quality partial"}>{entry.quality.status === "valid" ? <CheckCircle2 /> : <ShieldAlert />}<strong>{entry.quality.status}</strong><small>{entry.quality.issues.length ? entry.quality.issues.join(" · ") : "Complete research record"}</small></div></section>
    <div className="metric-grid"><MetricCard label="Season total" value={String(entry.summary.total_points)} /><MetricCard label="Overall rank" value={`#${entry.summary.overall_rank.toLocaleString()}`} /><MetricCard label="League rank" value={`#${entry.summary.league_rank.toLocaleString()}`} /><MetricCard label="Captain return" value={`${entry.summary.captain_points ?? 0} pts`} detail="Before multiplier" /></div>
    <div className="content-grid journal-detail-grid"><section className="surface"><div className="section-heading"><div><span>DECISION AT DEADLINE</span><h2>What the system knew</h2></div><Clock3 size={18} /></div>{entry.decision.captured ? <div className="journal-decision"><strong>{entry.decision.model_version}</strong><p>Packet {entry.decision.packet_status ?? "captured"} · {entry.decision.v5_projection_version ?? "V5 unavailable"}</p><small>Decision ID {entry.decision.decision_id}</small></div> : <div className="journal-missing"><ShieldAlert /><div><strong>Historical deadline bundle unavailable</strong><p>This GW predates the journal capture system. Outcome data remain valid; prediction evaluation is intentionally incomplete.</p></div></div>}</section>
      <section className="surface"><div className="section-heading"><div><span>WHAT WE LEARNED</span><h2>Gameweek memory</h2></div><Lightbulb size={18} /></div><ul className="journal-lessons">{entry.learning.automated.map((lesson) => <li key={lesson}>{lesson}</li>)}</ul>{entry.learning.public_lesson ? <blockquote>{entry.learning.public_lesson}</blockquote> : <p className="journal-private-note">Private guided reflection is kept outside this dashboard.</p>}</section></div>
    <section className="surface table-surface"><div className="section-heading"><div><span>SQUAD OUTCOME</span><h2>Starting XI and bench</h2></div><span className="section-chip">{starters.reduce((sum, player) => sum + player.points * player.multiplier, 0)} scoring points</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Player</th><th>Position</th><th>Club</th><th>Minutes</th><th>Role</th><th>Points</th></tr></thead><tbody>{[...starters, ...bench].map((player) => <tr key={player.element}><td><strong>{player.name}</strong></td><td>{player.position}</td><td>{player.team}</td><td>{player.minutes}</td><td>{player.is_captain ? "Captain" : player.is_vice_captain ? "Vice" : player.multiplier ? "Starter" : "Bench"}</td><td><strong>{player.points * player.multiplier}</strong></td></tr>)}</tbody></table></div></section>
    <div className="content-grid journal-research-grid"><section className="surface"><div className="section-heading"><div><span>LEAGUE CONTEXT</span><h2>How the field behaved</h2></div><Trophy size={18} /></div><div className="journal-signal-list">{entry.league.captain_choices.slice(0, 5).map((row) => <div key={row.name}><span>{row.name}</span><i><b style={{ width: `${Math.min(100, row.percentage)}%` }} /></i><strong>{row.percentage}%</strong></div>)}</div></section><section className="surface"><div className="section-heading"><div><span>MODEL EVALUATION</span><h2>Prediction accountability</h2></div><BrainCircuit size={18} /></div><div className="journal-models"><article><span>V5 LAB</span><strong>{entry.evaluation.v5.mae ?? "—"}</strong><small>MAE · {entry.evaluation.v5.rows} rows</small></article><article><span>FPL BASELINE</span><strong>{entry.evaluation.fpl_ep_next.mae ?? "—"}</strong><small>MAE · {entry.evaluation.fpl_ep_next.rows} rows</small></article></div></section></div>
    <section className="journal-provenance"><Database /><div><strong>Research provenance</strong><p>{entry.provenance.sources.join(" · ")}</p><small>Record {entry.record_hash.slice(0, 16)}…</small></div></section>
  </div>;
}
