import { LeagueSwitcher, resolveLeague } from "@/components/league-switcher";
import { EliteManagerMonitor, EliteSquadMatrix } from "@/components/elite-manager-monitor";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { PlayerCard } from "@/components/player-card";
import { getLeagueData } from "@/lib/data";
import { analyzeElite } from "@/lib/elite";
import { formatMYT } from "@/lib/format";
import type { Bootstrap, Pick, Position } from "@/lib/types";

const positionOrder: Position[] = ["GKP", "DEF", "MID", "FWD"];

export default async function ElitePage({ searchParams }: { searchParams: Promise<{ league?: string; gw?: string }> }) {
  const params = await searchParams;
  const selected = resolveLeague(params.league), requestedGw = params.gw ? Math.max(1, Math.min(38, Number(params.gw) || 1)) : undefined, data = await getLeagueData(selected.id, requestedGw), insight = analyzeElite(data.managers);
  const ownershipById = new Map(insight.ownership.map((player) => [player.element, player.elitePercentage]));
  const positiveEdges = [...insight.ownership].sort((a, b) => b.edge - a.edge).slice(0, 8), avoidEdges = [...insight.ownership].sort((a, b) => a.edge - b.edge).slice(0, 8);
  const snapshotNote = data.liveProvisional ? ` GW${data.gameweek} standings are live from official FPL; final points and ranks may still change. Research uses ${data.dataStatus?.hydration?.loaded ?? 0} of ${data.dataStatus?.hydration?.expected ?? data.managers.length} hydrated squads; unhydrated managers are excluded from Elite metrics.` : data.requestedGameweek !== data.gameweek ? ` GW${data.requestedGameweek} is live but not finalized; this view is showing the latest complete GW${data.gameweek} snapshot.` : "";
  const freshnessLabel = data.liveProvisional ? `GW${data.gameweek} live · ${formatMYT(data.fetchedAt) ?? "time unavailable"}` : `GW${data.gameweek} finalized snapshot · ${formatMYT(data.fetchedAt) ?? "time unavailable"}`;
  return <div className="page-stack"><PageHeader eyebrow="ELITE TRACKER" title={`${selected.name} · Top 5%`} description={`Detailed behavior of the best ${insight.elite.length} managers from ${data.managers.length.toLocaleString()} tracked entries.${snapshotNote}`} freshnessLabel={freshnessLabel} /><LeagueSwitcher selected={selected.id} pathname="/elite" />
    <section className="metric-grid"><MetricCard label="Elite cohort" value={insight.elite.length.toLocaleString()} detail={data.liveProvisional ? "Top 5% by latest verified overall rank" : "Top 5% by overall rank"} /><MetricCard label="Average GW" value={insight.averageGw.toFixed(1)} detail={`Median ${insight.medianGw.toFixed(1)}`} /><MetricCard label="Average value" value={`£${insight.averageValue.toFixed(1)}m`} detail={`Avg rank ${insight.averageRank.toLocaleString()}`} /><MetricCard label="Your gap" value={data.manager ? `${(data.manager.gw_points - insight.averageGw).toFixed(1)}` : "—"} detail={data.manager ? `${data.manager.gw_points} vs ${insight.averageGw.toFixed(1)}` : "Your team is not in this league"} tone={data.manager ? (data.manager.gw_points >= insight.averageGw ? "positive" : "warning") : undefined} /></section>
    <div className="content-grid elite-template-layout"><section className="surface pitch-surface elite-pitch-surface"><div className="section-heading"><div><span>CONSENSUS SQUAD</span><h2>Elite template · {insight.commonFormation}</h2></div><span className="section-chip">11 starters + 4 bench</span></div><EliteTemplate squad={insight.template} bootstrap={data.bootstrap} ownership={ownershipById} /></section><section className="surface"><div className="section-heading"><div><span>OWNERSHIP</span><h2>Template hierarchy</h2></div><span className="section-chip">Squad / XI</span></div><div className="signal-list elite-scroll-list">{insight.ownership.slice(0, 25).map((player) => <article key={player.element}><div><strong>{player.name}</strong><small>{player.position} · {player.team} · {player.starterPercentage.toFixed(1)}% started</small></div><span>{player.elitePercentage.toFixed(1)}%</span><div className="mini-track"><i style={{ width: `${player.elitePercentage}%` }} /></div></article>)}</div></section></div>
    <div className="elite-analysis-grid"><Distribution title="Starting formations" rows={insight.formations.slice(0, 7)} suffix="managers" /><Distribution title="Captaincy concentration" rows={insight.captaincy.slice(0, 8)} suffix="captains" /><Distribution title="GW points distribution" rows={insight.pointsDistribution} suffix="managers" /></div>
    <div className="content-grid elite-edge-grid"><EdgePanel title="Players elite favour" subtitle="Ownership above league baseline" rows={positiveEdges} /><EdgePanel title="Players elite avoid" subtitle="Ownership below league baseline" rows={avoidEdges} negative /></div>
    <div className="content-grid elite-edge-grid"><section className="surface"><div className="section-heading"><div><span>TRANSFER MARKET</span><h2>Elite transfer consensus</h2></div><span className="section-chip">GW{data.gameweek} snapshot</span></div>{insight.transfers.length ? <div className="ranked-list">{insight.transfers.slice(0, 12).map((row, index) => <article key={row.name}><span>{index + 1}</span><strong>{row.name}</strong><b>{row.count}<small>{row.percentage.toFixed(1)}%</small></b></article>)}</div> : <div className="empty-state"><h3>No transfer activity</h3><p>No transfer details were recorded for this cohort.</p></div>}</section><section className="surface"><div className="section-heading"><div><span>CHIPS & STRUCTURE</span><h2>Cohort behavior</h2></div><span className="section-chip">GW{data.gameweek} snapshot</span></div><div className="elite-summary-list"><article><span>Most common formation</span><strong>{insight.commonFormation}</strong></article><article><span>Top captain</span><strong>{insight.captaincy[0]?.name ?? "—"} · {insight.captaincy[0]?.percentage.toFixed(1) ?? "0.0"}%</strong></article><article><span>Average total points</span><strong>{insight.averageTotal.toFixed(1)}</strong></article><article><span>Highest GW score</span><strong>{insight.topScore}</strong></article>{insight.chips.slice(0, 4).map((chip) => <article key={chip.name}><span>{chip.name}</span><strong>{chip.count} managers</strong></article>)}</div></section></div>
    <details className="research-disclosure"><summary><span><b>DEEP RESEARCH</b><strong>Player-by-manager matrix</strong><small>Compare the leading 16 elite squads only when you need lineup-level detail.</small></span><em>Open</em></summary><section className="surface"><div className="section-heading"><div><span>ELITE SQUADS</span><h2>Player-by-manager comparison</h2><p>Compare the highest-owned players across the leading 16 elite squads. C and V show captaincy.</p></div><span className="section-chip">Top 16 managers</span></div><EliteSquadMatrix managers={insight.managerRows} /></section></details>
    <details className="research-disclosure"><summary><span><b>DEEP RESEARCH</b><strong>Full elite manager directory</strong><small>Search the complete top-5% cohort and inspect an individual squad.</small></span><em>Open</em></summary><section className="surface table-surface"><div className="section-heading"><div><span>ELITE MANAGERS</span><h2>Monitor every top-5% squad</h2><p>Search the cohort and open any manager to inspect their actual starting XI and bench.</p></div><span className="section-chip">Top {insight.managerRows.length}</span></div><EliteManagerMonitor managers={insight.managerRows} bootstrap={data.bootstrap} gameweek={data.gameweek} templateIds={insight.template.map((pick) => pick.element)} /></section></details>
  </div>;
}

function EliteTemplate({ squad, bootstrap, ownership }: { squad: Pick[]; bootstrap: Bootstrap; ownership: Map<number, number> }) {
  const starters = squad.slice(0, 11), bench = squad.slice(11, 15);
  const meta = (pick: Pick) => `${(ownership.get(pick.element) ?? 0).toFixed(0)}% owned`;
  return <div className="squad-view"><section className="pitch elite-pitch" aria-label="Elite consensus starting eleven">{positionOrder.map((position) => <div className={`pitch-row ${position.toLowerCase()}`} key={position}>{starters.filter((player) => player.position === position).map((player) => <PlayerCard key={player.element} pick={player} bootstrap={bootstrap} meta={meta(player)} />)}</div>)}</section><div className="bench"><div className="bench-heading"><span>Consensus bench</span><small>{bench.length} substitutes</small></div><div className="bench-grid">{bench.map((player) => <PlayerCard key={player.element} pick={player} bootstrap={bootstrap} meta={meta(player)} />)}</div></div></div>;
}

function Distribution({ title, rows, suffix }: { title: string; rows: Array<{ name?: string; label?: string; count: number; percentage: number }>; suffix: string }) {
  const maximum = Math.max(1, ...rows.map((row) => row.count));
  return <section className="surface"><div className="section-heading"><div><span>BREAKDOWN</span><h2>{title}</h2></div></div><div className="distribution-list">{rows.map((row) => <article key={row.name ?? row.label}><div><strong>{row.name ?? row.label}</strong><span>{row.count} {suffix} · {row.percentage.toFixed(1)}%</span></div><div className="distribution-track"><i style={{ width: `${row.count / maximum * 100}%` }} /></div></article>)}</div></section>;
}

function EdgePanel({ title, subtitle, rows, negative = false }: { title: string; subtitle: string; rows: Array<{ element: number; name: string; position: string; team: string; elitePercentage: number; leaguePercentage: number; edge: number }>; negative?: boolean }) {
  return <section className="surface"><div className="section-heading"><div><span>{negative ? "ANTI-TEMPLATE" : "ELITE EDGE"}</span><h2>{title}</h2><p>{subtitle}</p></div></div><div className="edge-list">{rows.map((player) => <article key={player.element}><div><strong>{player.name}</strong><small>{player.position} · {player.team}</small></div><span>Elite {player.elitePercentage.toFixed(1)}%</span><span>League {player.leaguePercentage.toFixed(1)}%</span><b className={player.edge >= 0 ? "positive" : "negative"}>{player.edge >= 0 ? "+" : ""}{player.edge.toFixed(1)}pp</b></article>)}</div></section>;
}
